### ISSUE TITLE
filetype was gone when execute jumpDefinition

### ISSUE THREAD

**Issue by heavenshell** [fannheyward/coc-deno#124] opened 2021-10-02 05:53 UTC
Hi.

When I type gd(coc-definition) and jump to the file, filetype was gone.
So, no syntax color and coc-deno does not work at the jumped file.

https://user-images.githubusercontent.com/56591/135705265-3d2a590a-c0a2-4e7e-82c6-d3e7e4383046.mp4

Step to reproduce
```typescript
const listener = Deno.listen({ port: 9000 });
console.log(listener)
```

1. Move cursol to `Deno` and type gd
2. Open preview list and select 1st one
3. `:set ft`
4. shows `ft=`

Thank you.

**Comment by yaegassy** [comment] 2021-10-05 02:17
Hi,

I don't know how to fix or adjust it, but it seems that some uri names are OK and some are not, depending on the uri name displayed in `deno/virtualTextDocument`.

**e.g.**:

- OK
  - `deno:/asset//lib.deno.ns.d.ts`
  - `deno:/asset//lib.deno.console.d.ts`
- NG
  - `deno:/asset//lib.deno.unstable.d.ts`
  - `deno:/asset//lib.deno.net.d.ts`

**DEMO**:

https://user-images.githubusercontent.com/188642/135949707-e866ca26-cb17-4f0d-bfce-4cce8889e540.mp4

**Comment by yaegassy** [comment] 2021-10-05 03:14
Hmmm... If I open it with `split`, `vsplit`, or `tab`, there seems to be no problem. There may be a possibility that `coc.nvim` itself needs to be adjusted.

https://user-images.githubusercontent.com/188642/135954257-2103100d-d168-4fd2-8ddf-16a328e9d583.mp4

**Comment by yaegassy** [comment] 2021-12-16 08:55
@fannheyward  This is about this issue. I have checked in my environment and confirmed that the problem is not occurring now. Confirmed with coc-deno 3.9.2, Confirmed with Vim and Neovim, It has been checked in master and release of coc.nvim.

**Comment by fannheyward** [comment] 2021-12-16 08:57
Maybe the new asset url format can be handled correctly in vim/nvim.

**Closed** 2021-12-23 01:25 UTC
