### ISSUE TITLE
Buffer for "jumpDefinition" is empty in deno v1.7.5

### ISSUE THREAD

**Issue by yaegassy** [fannheyward/coc-deno#69] opened 2021-02-22 03:39 UTC
## Description

This may be a problem with "deno lsp" itself, but I would like to report it since it is not a problem with v1.7.4.

Also, I'm sorry if the problem is only with my environment.

However, we have confirmed that VSCode's `vscode_deno v3.0.1` can "Go to definitions" even with deno v1.7.5.

### [OK] coc-deno + deno v1.7.4

![coc-deno_1_7_4](https://user-images.githubusercontent.com/188642/108653818-cb8bed80-750a-11eb-98e0-328e8e965251.gif)

### [NG] coc-deno + deno v1.7.5 (empty buffer)

![coc-deno_1_7_5](https://user-images.githubusercontent.com/188642/108653856-e3637180-750a-11eb-873d-05cd09053191.gif)

### [OK] vscode_deno v3.0.1 + deno v1.7.5

![vscode_deno_3_0_1_deno_1_7_5](https://user-images.githubusercontent.com/188642/108653898-f8d89b80-750a-11eb-809e-20ed47b95a16.gif)

## Misc

An older version of deno can be downloaded from GitHub release.

https://github.com/denoland/deno/releases

**Comment by fannheyward** [comment] 2021-02-22 03:49
Reproduced.

**Comment by yaegassy** [comment] 2021-02-22 05:53
"deno" seems to be able to download binaries at the commit hash level.

<https://dl.deno.land/>

I did some research based on that, and found that this symptom seems to be occurring from this commit.

<https://github.com/denoland/deno/commit/2225e83da2d118678e3df1e2801af195166bc65a>

**Comment by fannheyward** [comment] 2021-02-22 06:37
Properly caused by https://github.com/denoland/deno/issues/9514 and https://github.com/denoland/deno/commit/2225e83da2d118678e3df1e2801af195166bc65a#diff-4ad030d88c2590103755c58d2eb7fab1c0ed94df17d42b65c51cafb863fb013aR93

In 1.7.4 and earlier LS returns `deno:///https/xxx`
in 1.7.5 LS returns `deno:/https/xxx`

**Comment by fannheyward** [comment] 2021-02-22 07:04
Leaves a comment in that issue, but I don't find the _stand_ format in LSP.

**Comment by yaegassy** [comment] 2021-02-22 08:09
Thank you for reporting the issue to deno itself.

I modified the code of "deno" itself and build. https://github.com/denoland/deno/blob/main/cli/lsp/urls.rs#L95

### from

`format!("deno:/{}", path)`

### to

`format!("deno://{}", path)`

I'm not sure if this is an appropriate fix, but I will continue to watch this issue first. https://github.com/denoland/deno/issues/9514#issuecomment-783140787

**Comment by fannheyward** [comment] 2021-02-22 11:12
Fixed in coc master https://github.com/neoclide/coc.nvim/pull/2905

**Closed by fannheyward** 2021-02-22 11:12 UTC

**Comment by yaegassy** [comment] 2021-02-22 12:26
I have confirmed that "jumpDefinition" works fine with both deno v1.7.5 and v1.7.4 versions.
